services:
  frontend:
    build: ./frontend
    container_name: tier_frontend
    command: yarn start
    ports:
      - 3000:3000
  backend:
    build: ./backend
    container_name: tier_backend
    command: uvicorn tier_backend.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80

